- name: Install MySQL for production ready server
  hosts: all
  become: True
  become_user: root
  vars:
    MySQL_root_pass: StrongP@ssw0rd
    mysql_user: "sammy"
    mysql_password: "password"
  tasks:
    - name: Set MySQL root password before installing
      debconf: name="mysql-server" question="mysql-server/root_password" value="{{ MySQL_root_pass | quote }}" vtype="password"
    - name: Confirm MySQL root password before installing
      debconf: name="mysql-server" question="mysql-server/root_password_again" value="{{ MySQL_root_pass | quote }}" vtype="password"
    - name: test1
      apt:
        package:
            - mysql-server
            - mysql-client
            - python3-mysqldb
        state: present
        force: yes
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
     - name: ensure mysql started
         service: name=mysqld state=started enabled=yes
     - name: update mysql root password for all root accounts from local servers
         mysql_user: name=root
               host="{{item}}"
               password="xxxxxxxxxxx"
               priv=*.*:ALL,GRANT
               login_user=root
               login_password=""
               state=present

          with_items:
              - localhost
              - 127.0.0.1
              - ::1
              - localhost
    - name :  ensure mysql started
   service: name=mysqld state=started enabled=yes
    - name: copy .cnf file to root
   copy: src=../files/.my.cnf dest=/root/ owner=root mode=600
     - name: Change Root password
   mysql_user: name=root password="xxxxxxxx" update_password=always
    - name: Removes the MySQL test database
      mysql_db: db=test state=absent login_password="" login_user=root

    - name: Create a new database called wordpress
      mysql_db:
        login_user: root
        login_password: "{{ MySQL_root_pass }}"
        name: wordpress
        state: present

    - name: Configure new MySQL user called wpuser
      mysql_user:
        login_user: root
        login_password: "{{ MySQL_root_pass }}"
        name: wpuser
        password: wpuser
        priv: 'wordpress.*:ALL'
