- name: Install MySQL for production ready server
  hosts: all
  become: True
  become_user: root
  vars:
    MySQL_root_pass: StrongP@ssw0rd
  tasks:
    - name: Set MySQL root password before installing
      debconf: name="mysql-server" question="mysql-server/root_password" value="{{ MySQL_root_pass | quote }}" vtype="password"
    - name: Confirm MySQL root password before installing
      debconf: name="mysql-server" question="mysql-server/root_password_again" value="{{ MySQL_root_pass | quote }}" vtype="password"
    - name: test1
      apt:
        package:
            - mysql-server
            - mysql-client
            - python3-mysqldb
        state: present
        force: yes
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
    - name: Secures the MySQL root user
      mysql_user: user="root" password="{{ MySQL_root_pass }}" host="{{item}}" login_password="{{ MySQL_root_pass }}" login_user=root
      with_items:
        - 127.0.0.1
        - localhost
        - ::1
        - ""
    - name: Removes the MySQL test database
      mysql_db: db=test state=absent login_password="" login_user=root

    - name: Create a new database called wordpress
      mysql_db:
        login_user: root
        login_password: "{{ MySQL_root_pass }}"
        name: wordpress
        state: present

    - name: Configure new MySQL user called wpuser
      mysql_user:
        login_user: root
        login_password: "{{ MySQL_root_pass }}"
        name: wpuser
        password: wpuser
        priv: 'wordpress.*:ALL'
