- name: Install MySQL for production ready server
  user: labsuser
  hosts: all
  become: True
  become_user: root
  vars:
    MySQL_root_pass: ReplaceWithYourPassword
  tasks:
    - name: Set MySQL root password before installing
      debconf: name="mysql-server" question="mysql-server/root_password" value="" vtype="password"
    - name: Confirm MySQL root password before installing
      debconf: name="mysql-server" question="mysql-server/root_password_again" value="" vtype="password"
    - name: test1
      apt:
        package:
            - mysql-server
            - mysql-client
            - python3-mysqldb
        state: present
        force: yes
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
    - name: Removes the MySQL test database
      mysql_db: login_unix_socket="/var/run/mysqld/mysqld.sock" db=test state=absent login_password="" login_user=root

    - name: Create a new database called wordpress
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: root
        login_password: ""
        name: wordpress
        state: present

    - name: Configure new MySQL user called wpuser
      mysql_user:
        login_user: root
        login_password: ""
        name: wpuser
        password: wpuser_password_replace_with_your_own
        priv: 'wordpress.*:ALL'
        login_unix_socket: /var/run/mysqld/mysqld.sock
